/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package course_test.course_service;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2022-11-03")
public enum PhoneType implements org.apache.thrift.TEnum {
  HOME(0),
  WORK(1),
  MOBILE(2),
  OTHER(3);

  private final int value;

  private PhoneType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static PhoneType findByValue(int value) { 
    switch (value) {
      case 0:
        return HOME;
      case 1:
        return WORK;
      case 2:
        return MOBILE;
      case 3:
        return OTHER;
      default:
        return null;
    }
  }
}
