package rever.etl.engagement.linquiry.config

object ListingInquiryFields {
  final val INQUIRY_ID = "inquiry_id"
  final val CREATED_TIME = "created_time"
  final val UPDATED_TIME_INQUIRY = "updated_time_inquiry"
  final val UPDATED_TIME = "updated_time"
  final val OWNER_ID = "owner_id"
  final val OWNER_TEAM = "owner_team"
  final val OWNER_EMAIL = "owner_email"
  final val OWNER_DEPARTMENT = "owner_department"
  final val OWNER_JOB_TITLE = "owner_job_title"
  final val LISTING_OWNER_ID = "listing_owner_id"
  final val INQUIRY_OWNER_ID = "inquiry_owner_id"
  final val LISTING_OWNER_EMAIL = "listing_owner_email"
  final val INQUIRY_OWNER_EMAIL = "inquiry_owner_email"
  final val LISTING_OWNER_JOB_TITLE = "listing_owner_job_title"
  final val INQUIRY_OWNER_JOB_TITLE = "inquiry_owner_job_title"
  final val INQUIRY_OWNER_TEAM = "inquiry_owner_team"
  final val LISTING_OWNER_TEAM = "listing_owner_team"
  final val INQUIRY_OWNER_DEPARTMENT = "inquiry_owner_department"
  final val LISTING_OWNER_DEPARTMENT = "listing_owner_department"
  final val LISTING_ID = "listing_id"
  final val PUBLISHED_TIME = "published_time"
  final val LISTING_STATUS = "listing_status"
  final val PROPERTY_TYPE = "property_type"
  final val NUM_BED_ROOM = "num_bed_room"
  final val SALE_PRICE = "sale_price"
  final val AREA_USING = "area_using"
  final val CITY = "city"
  final val UPDATED_TIME_LISTING = "updated_time_listing"
  final val DISTRICT = "district"
  final val WARD = "ward"
  final val PROJECT_NAME = "project_name"

  final val LISTING_IDS = "listing_ids"
}
